package com.uni.realtime.gameengine.definition;

import java.util.List;

/**
 * PO V2.2 §3.1 (Group A, Học thuật tự nhập): one multiple-choice question, entered upfront rather
 * than generated by an LLM. {@code correctOptionIndex} indexes into {@code options} (A=0..D=3 per
 * §6 rule 2 -- default multiple choice 1/4); the engine never reads it back to a client, only uses
 * it to build the {@code correctAnswerIds} an actor's {@code StartQuestion} expects.
 */
public record Question(String questionText, List<String> options, int correctOptionIndex) {}
